receivers:
  filelog:
    include:
      # - /var/log/pods/*/*/*.log # e.g. for kubernetes log files
      # - /var/lib/docker/containers/*/*log # for local docker desktop but needed some permissions fixes
      - /etc/locallokilogs.log # Add logs manually.
    # exclude:     # can be useful for excluding self logs from otel-collector itself for any reason
    start_at: beginning
    include_file_path: false
    include_file_name: false
    retry_on_failure:
      enabled: false
    operators:
      - type: regex_parser
        regex: '^(?P<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{3}.*) (?P<sev>[A-Z]*) (?P<msg>.*)$'
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        severity:
          parse_from: attributes.sev

processors:
  batch:

exporters:
  logging:
    verbosity: detailed
  loki:
    endpoint: 'http://loki:3100/loki/api/v1/push'

service:
  pipelines:
    logs:
      receivers: [ filelog ]
      processors: [ batch ]
      exporters: [ logging, loki ]

#Read more about file receiver and exporter its limitation and configurations
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver
# https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md