## Option 2 via Promtail client
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: 'http://loki:3100/loki/api/v1/push'

scrape_configs:
  #  - job_name: system  # Your local promtail self system log scrapping
  #    static_configs:
  #      - targets:
  #          - localhost
  #        labels:
  #          job: varlogs
  #          __path__: /var/log/*log
  - job_name: container # All containers logs scrapping running locally, Need to fix does not work as expected for labeling/isolation
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerslog
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - docker: { } #Docker stage is just a convenience wrapper for following definition:
  #      - json:
  #        expressions:
  #          output: log
  #          stream: stream
  #          timestamp: time
  #      - labels:
  #          stream:
  #      - timestamp:
  #          source: timestamp
  #          format: RFC3339Nano
  #      - output:
  #          source: output
  # Following is how we could do custom labelling configs for  individual container... but hard to do it.  Need to fix
  # does not work as expected due to too many containers log in different formats. Heterogeneous logs, may be parser or something I should consider
#  - job_name: custom-config
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: customAppLog
#          __path__: /var/lib/docker/containers/*/*log
#    pipeline_stages:
#      - json:
#          expressions:
#            timestamp: timestamp
#            level: level
#            thread: thread
#            class: logger
#            message: message
#            context: context
#      - labels:
#          level:
#          class:
#          context:
#          thread:
#      - timestamp:
#          format: RFC3339
#          source: timestamp
#      - output:
#          source: message
  - job_name: app_scrape # application log scrapping job from docker demon directly
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 2s
        filters:
          - name: label
            values: [ "logging=promtail" ]
    relabel_configs:
      - source_labels: [ '__meta_docker_container_name' ]
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: [ '__meta_docker_container_log_stream' ]
        target_label: 'logstream'
      - source_labels: [ '__meta_docker_container_label_logging_jobname' ]
        target_label: 'job'

#Refernce and config of promtail -> https://grafana:com/docs/loki/latest/send-data/promtail/configuration/#docker_sd_config: